version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.34.0
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:4.34.0
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  hub:
    image: selenium/hub:4.34.0
    ports:
      - "4444:4444"